lastOrderedProduct = {
  MetodosPago: ["cash", "transferencia", "pago móvil", "tarjeta"],
  Productos: [
    {
      cantidadDisponible: "2",
      categoria: [Array],
      descripcion:
        "2x1 en pollo a la brasa, acompañado de papas fritas y ensalada",
      diaRetiro: "Hoy",
      horaRetiro: "06:30 - 10:59",
      id: 1,
      nombre: "Plato de pollo",
      precioAntes: "10.00",
      precioVenta: "4.80",
    },
    {
      cantidadDisponible: "1",
      categoria: [Array],
      descripcion:
        "Caja sorpresa con 2 platos principales, 2 postres y 2 bebidas",
      diaRetiro: "Mañana",
      horaRetiro: "07:15 - 11:45",
      id: 2,
      nombre: "Caja sorpresa",
      precioAntes: "18.00",
      precioVenta: "9.00",
    },
  ],
  UrlDireccion: "https://maps.app.goo.gl/KEikhkDyTsXDkwk47",
  calificaciones: [
    {
      Fecha: "2024-05-01",
      Nombre: "Juan Pérez",
      calificacion: 4.5,
      comentario: "Excelente servicio, la comida es deliciosa",
    },
    {
      Fecha: "2024-05-02",
      Nombre: "María López",
      calificacion: 4,
      comentario: "La comida es buena, pero el servicio es lento",
    },
    {
      Fecha: "2024-05-03",
      Nombre: "Carlos Martínez",
      calificacion: 1,
      comentario: "La comida es deliciosa y el servicio es excelente",
    },
    {
      Fecha: "2024-05-04",
      Nombre: "Ana González",
      calificacion: 2,
      comentario: "El ambiente es agradable y la comida es sabrosa",
    },
    {
      Fecha: "2024-05-05",
      Nombre: "Luis Ramírez",
      calificacion: 3,
      comentario: "El servicio podría ser mejor, pero la comida es buena",
    },
    {
      Fecha: "2024-05-06",
      Nombre: "Sofía Torres",
      calificacion: 4,
      comentario: "Me encanta la variedad del menú",
    },
    {
      Fecha: "2024-05-07",
      Nombre: "Miguel Sánchez",
      calificacion: 5,
      comentario: "Los precios son razonables para la calidad de la comida",
    },
    {
      Fecha: "2024-05-08",
      Nombre: "Isabel Fernández",
      calificacion: 2,
      comentario: "La comida es buena, pero el lugar es un poco ruidoso",
    },
    {
      Fecha: "2024-05-09",
      Nombre: "José García",
      calificacion: 3,
      comentario: "El personal es amable y la comida es excelente",
    },
    {
      Fecha: "2024-05-10",
      Nombre: "Patricia Rodríguez",
      calificacion: 4,
      comentario: "La comida es promedio, pero el servicio es rápido",
    },
    {
      Fecha: "2024-05-11",
      Nombre: "Roberto Hernández",
      calificacion: 1,
      comentario: "El lugar es limpio y la comida es deliciosa",
    },
    {
      Fecha: "2024-05-12",
      Nombre: "Daniela Castro",
      calificacion: 2,
      comentario: "La comida es buena, pero el lugar es un poco pequeño",
    },
    {
      Fecha: "2024-05-13",
      Nombre: "Raúl Morales",
      calificacion: 3,
      comentario: "El servicio es excelente y la comida es sabrosa",
    },
    {
      Fecha: "2024-05-14",
      Nombre: "Lucía Ruiz",
      calificacion: 4,
      comentario: "La comida es deliciosa, pero el servicio podría ser mejor",
    },
    {
      Fecha: "2024-05-15",
      Nombre: "Javier Ortiz",
      calificacion: 5,
      comentario: "El lugar es agradable y la comida es buena",
    },
    {
      Fecha: "2024-05-16",
      Nombre: "Laura Muñoz",
      calificacion: 1,
      comentario: "El servicio es rápido y la comida es sabrosa",
    },
    {
      Fecha: "2024-05-17",
      Nombre: "Francisco Díaz",
      calificacion: 2,
      comentario: "La comida es promedio, pero el lugar es agradable",
    },
    {
      Fecha: "2024-05-18",
      Nombre: "Marta Jiménez",
      calificacion: 3,
      comentario: "El servicio es lento, pero la comida es buena",
    },
    {
      Fecha: "2024-05-19",
      Nombre: "Pedro Medina",
      calificacion: 4,
      comentario: "La comida es deliciosa y el lugar es limpio",
    },
    {
      Fecha: "2024-05-20",
      Nombre: "Gloria Chávez",
      calificacion: 5,
      comentario: "El servicio es excelente, pero la comida es promedio",
    },
    {
      Fecha: "2024-05-21",
      Nombre: "Adriana Romero",
      calificacion: 1,
      comentario: "La comida es sabrosa y los precios son razonables",
    },
    {
      Fecha: "2024-05-22",
      Nombre: "Fernando Vargas",
      calificacion: 2,
      comentario: "El lugar es ruidoso, pero la comida es buena",
    },
  ],
  categoria: ["Plato principal", "Caja sorpresa", "Postre", "Otros"],
  cocina: "Pollo en brasa y parrilla",
  direccion: "Trans. 3, Qta Guio, con Av 3, Caracas 1060, Distrito Capital",
  distancia: "1.5",
  id: 1,
  nombre: "El Coyuco",
  ordenesCantidad: "200",
  urlImagenLogo:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/d49a502485ec5cfa23e5bb59bc169df6a240c31ae56c86b3ad9ef8f1e5bb28ba?apiKey=64cf540a2469411fb888e6001ea1b7f2&",
  urlImagenPortada:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/164d420ddd7ad34c6edf2890f7912b900b98b29f58d00cd7cb13fba47b580fcb?apiKey=64cf540a2469411fb888e6001ea1b7f2&",
};
